name: Run tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  setup-node_modules:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - uses: "nick-fields/retry@v2.8.3"
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm fetch --ignore-scripts

  ci-api-gateway:
    needs: setup-node_modules
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Start postgresql containers for testing
        run: docker-compose up -d postgresql
      - name: Install dependencies
        uses: nick-fields/retry@v2.8.3
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm install --frozen-lockfile
      - name: Run linter
        run: cd packages/api-gateway && pnpm lint
      - name: Run test suite
        run: cd packages/api-gateway && pnpm test:ci
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.node-version == 20 }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/api-gateway/coverage/clover.xml
          fail_ci_if_error: true
      - name: Add PR coverage report
        if: ${{ always() && github.event_name == 'pull_request' && matrix.node-version == 20 }}
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./packages/api-gateway/coverage/coverage-summary.json
          title: Coverage Report
          summary-title: Summary
          badge-title: Coverage
          hide-comment: false
          create-new-comment: false
          hide-summary: false
          # junitxml-title: My JUnit Title
          # junitxml-path: ./app/coverage/clover.xml
          report-only-changed-files: true
          coverage-title: File Coverage
          coverage-path: ./packages/api-gateway/coverage/coverage.txt
