name: Release & Publish

on:
  push:
    tags:
      - "@bitify*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install modules
        uses: nick-fields/retry@v2.8.3
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm install
      - name: Build
        run: |
          PATH="$(node ./scripts/get-package-from-tag.js '${{  github.ref_name }}')"
          cd ${PATH}
          pnpm build
      - name: Publish to npm
        run: |
          PATH="$(node ./scripts/get-package-from-tag.js '${{  github.ref_name }}')"
          cd ${PATH}
          pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
