name: Release & Publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: "The package name to be released (e.g @bitify/api-gateway). If empty every packages will be released"
        type: string

jobs:
  setup-node_modules:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - uses: "nick-fields/retry@v2.8.3"
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm fetch --ignore-scripts

  publish:
    needs: setup-node_modules
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: write
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Install dependencies
        uses: nick-fields/retry@v2.8.3
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm install --frozen-lockfile
      - name: Release packages
        run: |
          git config --global user.email "fasenderos@gmail.com"
          git config --global user.name "Andrea Fassina"
          git config -l
          if [! -z "${{ github.event.inputs.package }}" ];
          then
            PATH="$(node ./scripts/get-package-from-tag.js '${{  github.ref_name }}')"
            if [! -z "$PATH" ]; then cd $PATH; fi
          fi
          pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
