name: Publish releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number to tag and release"
        required: true
        type: string

jobs:
  release-npm:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: pnpm install
        uses: nick-fields/retry@v2.8.3
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm install
      - name: Change version number and sync
        run: |
          node scripts/update-version.mjs ${{ inputs.version }}
          sh scripts/sync-version.sh
      - name: update lockfile
        uses: nick-fields/retry@v2.8.3
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm install
      - name: Create and publish version
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: release version ${{ inputs.version }}"
          title: "chore: release version ${{ inputs.version }}"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
